"""
Django settings for authroot project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# TODO generate secret key from key server
SECRET_KEY = 'django-insecure-y=3t(^9=4s!wycp5ymid+)8qg)z&fb4h51)-^-q3dxkr!&_o-8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # TODO remove DEBUG

ALLOWED_HOSTS = [ '*' ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.staticfiles',
    'django_prometheus',

    'rest_framework_statelessauth'
]

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'rest_framework_statelessauth.middlewares.AuthMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware'
]

ROOT_URLCONF = 'authroot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'authroot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# TODO get key from key server
SIMPLE_PRIVATE_KEY = b"""-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIGQfqIs7GTCodOdyotgCS31ZhkMVaRgZK9W2uwvycKcioAoGCCqGSM49
AwEHoUQDQgAEqoyrOEudfh176TbcpINTbvPh9GThSY5K5lEWlTN4QteJ5t8//NJ4
O+Vf2Wi5I/XH16nmJI1agVvRIsVCGyJk5Q==
-----END EC PRIVATE KEY-----"""

from jose.backends.rsa_backend import RSAKey
from jose.backends.ecdsa_backend import ECDSAECKey
from rest_framework_statelessauth.engine.refresh import RefreshEngine
from rest_framework_statelessauth.contrib.auth.wire import UserWire
from rest_framework_statelessauth.contrib.auth.views import user_acquire_view

SL_AUTH_KEY_BACKENDS = {
    "default": ECDSAECKey( SIMPLE_PRIVATE_KEY, 'ES256' )
}
SL_AUTH_ENGINES = {
    "default": RefreshEngine( "default", UserWire(), user_acquire_view )
}

SL_AUTH_MIDDLEWARES = {}

PROMETHEUS_METRIC_NAMESPACE = ""
